### ISSUE TITLE
Configuring when/how melded

### ISSUE THREAD

**Issue by lorensr** [splendido/meteor-accounts-meld#32]
Hi, great package, thanks!

1. When melding, can you configure which account gets deleted? Eg delete the one that was just created, keeping the one with the oldest `createdAt`?
2. "In case a new service is added to the current user object without the need of any meld action, the serviceAddedCallback can be used to update, e.g., the user profile." In what circumstances is a new service added to an existing account instead of a meld happening between two accounts?

**Comment by splendido** [comment]
Hi @lorensr,

for now there's no choice for 1: the newly logged in user is the one kept while the one being merged with it is later deleted.

For 2. a simple case is the addition of a new service to the ones the user is using. This happens when the user is already logged in and `Meteor.loginWith<service>` is called (a OAuth login button is clicked)

Hope this might help

**Comment by lorensr** [comment]
Got it, thanks!
